# Generated by Django 5.0.4 on 2024-08-08 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('playlistId', models.CharField(max_length=50)),
                ('createdBy', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('itemCount', models.IntegerField()),
                ('url', models.URLField(max_length=150)),
                ('player', models.CharField(max_length=300)),
                ('cover', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=150)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courses', models.ManyToManyField(related_name='fav_courses', to='education.course')),
            ],
        ),
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('E', 'Enrolled'), ('P', 'In Progress'), ('C', 'Completed')], max_length=15)),
                ('courses', models.ManyToManyField(related_name='user_courses', to='education.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itemId', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('position', models.IntegerField()),
                ('publishedAt', models.DateTimeField()),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.course')),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='education.thumbnail')),
            ],
        ),
    ]
