# Generated by Django 5.0.4 on 2024-08-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_course_cover'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorites',
            new_name='Favorite',
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courseitem',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
