# Generated by Django 5.0.4 on 2024-08-17 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_delete_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='courses',
            new_name='favorite_courses',
        ),
        migrations.RemoveField(
            model_name='learning',
            name='courses',
        ),
        migrations.AddField(
            model_name='learning',
            name='enrolled_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='education.course'),
            preserve_default=False,
        ),
    ]
