# Generated by Django 5.0.4 on 2024-09-27 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSymbol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('market', models.CharField(choices=[('us', 'us'), ('europe', 'europe'), ('asia', 'asia')], max_length=50)),
                ('link', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserStock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('priceOnPurchase', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('stock', models.ManyToManyField(to='invest.stocksymbol')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
