# Generated by Django 5.0.4 on 2024-09-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStock',
        ),
    ]
