# Generated by Django 5.0.4 on 2024-10-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='StockExchange',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
    ]
