# Generated by Django 5.0.4 on 2024-10-04 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invest', '0002_remove_stock_exchange_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockExchange',
            fields=[
                ('mic', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('exchange_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
                ('currency_symbol', models.CharField(max_length=10)),
                ('link', models.URLField()),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invest.stockexchange')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price_on_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('purchased_on', models.DateTimeField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invest.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
