# Generated by Django 5.0.4 on 2024-09-28 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_userstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstock',
            name='purchased_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
