# Generated by Django 5.0.4 on 2024-10-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0006_rename_transactionhistory_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total_expense',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purchased_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
